name: Build

on: [push, pull_request]

jobs:
  build-linux:
    name: Linux build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release .
          make package

      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: publish-zip
          path: NadekoBot.zip

      - name: Upload deb
        uses: actions/upload-artifact@v2
        with:
          name: publish-deb
          path: NadekoBot.deb