name: Build

on: [push, pull_request]

jobs:
  build-linux:
    name: Linux build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build
        run: dotnet publish -c Release

      - name: Upload publish folder
        uses: actions/upload-artifact@v4
        with:
          name: publish-linux
          path: src/NadekoBot/bin/Release/net8.0/linux-x64/publish
