---
name: Build

on: [push, pull_request]

jobs:
  build-linux:
    name: Linux build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: dotnet publish -c Release

      - name: Copy extra files
        run: |
            cp -r src/NadekoBot/bin/Release/netcoreapp3.1/linux-x64/data src/NadekoBot/bin/Release/netcoreapp3.1/linux-x64/publish

      - name: Upload publish folder
        uses: actions/upload-artifact@v2
        with:
          name: publish-linux
          path: src/NadekoBot/bin/Release/netcoreapp3.1/linux-x64/publish
